# Generated by Django 3.0.6 on 2020-05-30 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('gymowner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('booking_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order_id', models.CharField(max_length=100)),
                ('payment_id', models.CharField(max_length=100)),
                ('payment_status', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('months', models.IntegerField()),
                ('new', models.BooleanField()),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymowner.GYM')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.GymUser')),
            ],
        ),
    ]
