# Generated by Django 3.0.6 on 2020-05-30 17:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_auto_20200530_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_timestamp',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
