# Generated by Django 3.0.6 on 2020-05-31 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_order_order_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_err_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_err_msg',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
