# Generated by Django 3.0.6 on 2020-07-03 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymowner', '0003_auto_20200630_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creduser',
            name='aadhar',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='creduser',
            name='contact',
            field=models.BigIntegerField(null=True),
        ),
    ]
